<?php


namespace Coff\SMF\Test;


use Coff\SMF\Machine;
use Coff\SMF\MachineInterface;
use Coff\SMF\StateEnum;
use Coff\SMF\Transition\TransitionInterface;

class SampleMachine extends Machine
{
    public function setMachineState(StateEnum $newState)
    {
        return parent::setMachineState($newState); // TODO: Change the autogenerated stub
    }

    public function assertOneToTwo()
    {

    }

    public function test(MachineInterface $machine, TransitionInterface $transition, $extra = null)
    {

    }
}