<?php


namespace Coff\SMF\Test;


use Coff\SMF\Machine;
use Coff\SMF\MachineInterface;
use Coff\SMF\StateEnum;
use Coff\SMF\Transition\TransitionInterface;

/**
 * Class SampleMachine
 * This is used for testing purposes only
 * @package Coff\SMF\Test
 */
class SampleMachine extends Machine
{
    /**
     * Only method access is changed for testing purposes
     *
     * @param StateEnum $newState
     * @return Machine
     * @throws \Coff\SMF\Exception\ConfigurationException
     * @throws \Coff\SMF\Exception\SchemaException
     * @throws \Coff\SMF\Exception\TransitionException
     */
    public function setMachineState(StateEnum $newState)
    {
        return parent::setMachineState($newState); // TODO: Change the autogenerated stub
    }

    public function assertOneToTwo()
    {

    }

    public function test(MachineInterface $machine, TransitionInterface $transition, $extra = null)
    {

    }
}