<?php


namespace Coff\SMF\Test;


use Coff\SMF\Machine;
use Coff\SMF\StateEnum;

class SampleMachine extends Machine
{
    public function setMachineState(StateEnum $newState)
    {
        return parent::setMachineState($newState); // TODO: Change the autogenerated stub
    }

    public function assertOneToTwo()
    {

    }

    public function test()
    {

    }
}